(defun get-chars-to-slash (dir)
  (let ((key (if (equal dir :left)
                 (kbd "S-Left")
                 (kbd "S-Right"))))
    (labels ((repeater (ctr)
               (stumpwm::send-meta-key (current-screen) key)
               (sleep 0.001)
               (let* ((sel (get-x-selection))
                      (start-pos (search "/" sel)))
                 (if (or start-pos (> ctr 20))
                     (subseq sel 1)
                     (repeater (+ 1 ctr))))))
      (repeater 0))))

(defun chars-to-slash (dir)
  (let ((back-key (if (equal dir :left)
                      (kbd "Right")
                      (kbd "Left")))
        (sel (get-chars-to-slash dir)))
    (stumpwm::send-meta-key (current-screen) back-key)
    sel))

(defun kill-to-slash (dir)
  (let* ((del-key (if (equal dir :left)
                      (kbd "BackSpace")
                      (kbd "Delete")))
         (chars (chars-to-slash dir))
         (num-chars (length chars)))
    (loop
       for i from 1 to num-chars
       do (stumpwm::send-meta-key (current-screen) del-key))))

(defcommand kill-to-slashes () ()
  (kill-to-slash :left)
  (kill-to-slash :right))

(define-key *top-map* (kbd "s-d") "kill-to-slashes")
