(defcommand get-chars-to (dir char) ((:direction "Kill direction: ") (:string "To: "))
  (let ((key (if (equal dir :left)
                 (kbd "S-Left")
                 (kbd "S-Right"))))
    (labels ((repeater (ctr)
               (stumpwm::send-meta-key (current-screen) key)
               (sleep 0.001)
               (let* ((sel (get-x-selection))
                      (start-pos (search char sel)))
                 (if (or start-pos (> ctr 20))
                     (subseq sel 1)
                     (repeater (+ 1 ctr))))))
      (repeater 0))))

(defun chars-to (dir char)
  (let ((back-key (if (equal dir :left)
                      (kbd "Right")
                      (kbd "Left")))
        (sel (get-chars-to dir char)))
    (stumpwm::send-meta-key (current-screen) back-key)
    sel))

(defcommand kill-to (dir char) ((:direction "Kill direction: ") (:string "To: "))
  (let* ((del-key (if (equal dir :left)
                      (kbd "BackSpace")
                      (kbd "Delete")))
         (chars (chars-to dir char))
         (num-chars (length chars)))
    (loop
       for i from 1 to num-chars
       do (stumpwm::send-meta-key (current-screen) del-key))))

(defcommand kill-to-surrounds (to) ((:string "To: "))
  (kill-to :left to)
  (kill-to :right to))
